FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# در اینجا باید به مسیر صحیح اشاره کنید
COPY ["Shop.RestApi/Shop-Ketab-Khoob.csproj", "./"]  
RUN dotnet restore "./Shop-Ketab-Khoob.csproj" 

COPY . . # کپی همه فایل‌ها به دایرکتوری /src
WORKDIR "/src/."
RUN dotnet build "Shop-Ketab-Khoob.csproj" -c Release -o /app/build 

FROM build AS publish
RUN dotnet publish "Shop-Ketab-Khoob.csproj" -c Release -o /app/publish  

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Shop-Ketab-Khoob.dll"]
